name: dropr_driver
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.2
  json_serializable: ^6.1.4
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  pinput: ^2.2.30
  image_picker: ^0.8.6
  camera: ^0.10.1
  syncfusion_flutter_gauges: ^20.4.44
  google_maps_flutter: ^2.2.3
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
